# theme.toml for the theme

name = "HUGO template for pbc.place's website"
license = "CC BY 3.0"
licenselink = "https://github.com/talmai/pbcplace-hugo-template/blob/master/LICENSE"
description = "HUGO template for pbc.place's website"
homepage = "https://github.com/talmai/pbcplace-hugo-template/"
tags = ["blog",'google-analytics', 'fast', 'modern', 'minimal', 'minimalistic', 'business', 'agency-template', 'white', 'light', 'multilingual', "bootstrap", "company", "portfolio", "projects", "responsive"]
features = ["blog", "company", "responsive", "seo-friendly"]
min_version = 0.19

[author]
  name = "Talmai Oliveira"
  homepage = "https://talm.ai"

[original]
  name = "Airspace Hugo"
  license = "CC BY 3.0"
  licenselink = "https://github.com/themefisher/airspace-hugo/blob/master/LICENSE"
  description = "Hugo port of the Themefisher’s Airspace theme"
  homepage = "https://github.com/themefisher/airspace-hugo"
  repo = "https://github.com/themefisher/airspace-hugo"
