title = "Airspace for Hugo"
baseURL = "https://www.example.com"
languageCode = "en-us"
theme = "pbcplace-hugo-template"

# The site's parameters
[params]

  # Google Analitycs
  googleAnalitycsID = "Your ID"
  description = "PBC Place's Hugo Template Theme"
  author = "talmai"
  
# Multilangual : BR / EN
[Languages]
    ############ 1 - Site em Portugues

  [Languages.br]
  languageName = "br"
  weight = 1
  languageCode = "pt-br"
  title = "FRANCAIS Airspace Hugo"
  dateFormat = "2 January 2006"
  home = "FR-Home"

  [Languages.br.menu]

    [[Languages.br.menu.header]]
      weight = 2
      name = "FR-Work"
      url = "/br/work"
    [[Languages.br.menu.header]]
      weight = 3
      name = "FR-Blog"
      url = "/br/blog"
    [[Languages.br.menu.header]]
      weight = 4
      name = "FR-Service"
      url = "/br/service"
    [[Languages.br.menu.header]]
      weight = 5
      name = "FR-Contact"
      url = "/br/contact"

    [[Languages.br.menu.footer]]
      weight = 1
      name = "FR-About us"
      url = "#"
    [[Languages.br.menu.footer]]
      weight = 2
      name = "FR-Contact us"
      url = "#"
    [[Languages.br.menu.footer]]
      weight = 3
      name = "FR-How it works"
      url = "#"
    [[Languages.br.menu.footer]]
      weight = 4
      name = "FR-Blog"
      url = "#"
    [[Languages.br.menu.footer]]
      weight = 5
      name = "FR-Terms"
      url = "#"


  [Languages.br.params]

    [Languages.br.params.slider]
      enable = true
      title = "Un marketing numérique & agence de design"
      subtitle = "FRANCAIS We love the Web and the work we do.<br/>We work closely with our clients to deliver the best possible solutions for their needs"

    [Languages.br.params.wrapper]
      enable = true
      image = "img/wrapper-img.png"
      title = "FRANCAIS About Us"
      italic = "FRANCAIS Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics"
      paragraph = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id"

    [Languages.br.params.blog]
      enable = true
      title = "FRANCAIS Get The Latest On What We're doing"
      subtitle = "FRANCAIS Catch up with us, anytime and anywhere"

    [Languages.br.params.feature]
      enable = true
      title = "FRANCAIS We believe in great ideas"
      content = "FRANCAIS Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus."
      [Languages.br.params.feature.button]
        caption = "View Works"
        url = "#"

    [Languages.br.params.call]
      enable = true
      title = "FRANCAIS We design delightful digital experiences."
      paragraph = "FRANCAIS Read more about what we do and our philosophy of design. Judge for yourself The work and results we’ve achieved for other clients, and meet our highly experienced Team who just love to design."

    [Languages.br.params.contact]
      enable = true
      title = "FRANCAIS Drop us a note"
      subtitle = "Don’t just take our word for it. Check out some of our latest work."
      [Languages.br.params.contact.form]
        name = "Your name"
        email = "Your email"
        subject = "Your subject"
        message = "Your message"
        button = "Send message"
      [Languages.br.params.contact.box]
        title = "Stop by for a visit"
        address = "North Main Street, Brooklyn Australia"
        email = "Email: contact@mail.com"
        phone = "Phone: +88 01672 506 744"
      [Languages.br.params.contact.gmaps]
        title = "We Also Count in Google Maps"

  ######## english language
  [Languages.en]
  languageName = "us"
    weight = 2
    languageCode = "en-us"
    title = "Airspace Hugo"
    dateFormat = "January 2, 2006"
    home = "Home"

    
  [Languages.en.menu]

    [[Languages.en.menu.header]]
      weight = 2
      name = "Work"
      url = "/work"
    [[Languages.en.menu.header]]
      weight = 3
      name = "Blog"
      url = "/blog"
    [[Languages.en.menu.header]]
      weight = 4
      name = "Service"
      url = "/service"
    [[Languages.en.menu.header]]
      weight = 5
      name = "Visit us"
      url = "/contact"

    [[Languages.en.menu.footer]]
      weight = 1
      name = "About us"
      url = "#"
    [[Languages.en.menu.footer]]
      weight = 2
      name = "Visit us"
      url = "/contact"
    [[Languages.en.menu.footer]]
      weight = 3
      name = "How it works"
      url = "#"
    [[Languages.en.menu.footer]]
      weight = 4
      name = "Blog"
      url = "#"
    [[Languages.en.menu.footer]]
      weight = 5
      name = "Terms"
      url = "#"

  [Languages.en.params.slider]
    enable = true
    title = "PBC PLACE<br> A Place for New Beginnings"
    subtitle = "We are a vibrant and exciting church with a contemporary worship celebration, a variety of expressions of praise, and a strong biblical grounding. Our activities are bilingual."

  [Languages.en.params.wrapper]
    enable = true
    image = "img/church_front_people.jpg"
    title = "About Us"
    italic = "We want to lead people to worship and serve God with joy and understanding, challenging them to: "
    paragraph = "Know Christ as Savior, to mature in the Christian life, to Participate in small groups, to Act in the ministry exercising your gifts in service to others, to Make disciples of Jesus, and to Support the local church, missionary projects and humanitarian actions."

  [Languages.en.params.blog]
    enable = true
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

  [Languages.en.params.feature]
    enable = true
    title = ""
    content = ""
    [Languages.en.params.feature.button]
      caption = "Watch us Live, Every Sunday @11AM"
      url = "http://live.pbc.place"

  [Languages.en.params.call]
    enable = true
    title = "We design delightful digital experiences."
    paragraph = "Read more about what we do and our philosophy of design. Judge for yourself The work and results we’ve achieved for other clients, and meet our highly experienced Team who just love to design."

  [Languages.en.params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [Languages.en.params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [Languages.en.params.contact.box]
      title = "Stop by for a visit"
      address = "47 Adams Avenus, Saugus, MA, 01906"
      email = "Email: office@pbc.place"
      phone = "Phone: (617) 354-4557"
    [Languages.en.params.contact.gmaps]
      title = "We are located in Saugus, easily accessible via US1 and next to the Square One Mall."
