#title = "PBC PLACE - Um Lugar para Novos Começos"
baseURL = "https://www.pbc.place/"
languageCode = "en-us"
theme = "pbcplace-hugo-template"

# The site's parameters
[params]

  # Google Analitycs
  googleAnalitycsID = "Your ID"
  description = "PBC Place's Hugo Template Theme"
  author = "talmai"
  
# Multilangual : BR / EN
[Languages]
    ############ 1 - Site em Portugues  

  [Languages.br]
  languageName = "br"
  weight = 1
  languageCode = "pt-br"
  title = "PBC PLACE - Um Lugar para Novos Começos"
  baseURL = "https://www.pbc.place/br/"
  dateFormat = "2 January 2006"
  home = "Principal"

  [Languages.br.menu]

    [[Languages.br.menu.header]]
      weight = 2
      name = "Cremos"
      url = "/believe"
    [[Languages.br.menu.header]]
      weight = 3
      name = "Nossas Atividades"
      url = "/activities"
    [[Languages.br.menu.header]]
      weight = 4
      name = "Como Chegar"
      url = "/contact"
    [[Languages.br.menu.header]]
      weight = 5
      name = "Doe"
      url = "/give"

    [[Languages.br.menu.footer]]
      weight = 2
      name = "Cremos"
      url = "/believe"
    [[Languages.br.menu.footer]]
      weight = 3
      name = "Nossas Atividades"
      url = "/activities"
    [[Languages.br.menu.footer]]
      weight = 4
      name = "Como Chegar"
      url = "/contact"
    [[Languages.br.menu.footer]]
      weight = 5
      name = "Doe"
      url = "/give"

  [Languages.br.params.slider]
    enable = true
    title = "PBC PLACE<br> Um Lugar para Novos Começos"
    subtitle = "Somos uma igreja alegre e vibrante com culto contemporâneo, com expressões variadas de adoração, louvor e mensagens bíblica. Nossas atividades são bilíngue (português-inglês)."

  [Languages.br.params.wrapper]
    enable = true
    image = "img/church_front_people.jpg"
    title = "Sobre Nossa Igreja"
    italic = "Queremos levar pessoas a adorarem e a servirem a Deus com alegria e entendimento, desafiando-as a: "
    [Languages.br.params.wrapper.content]
      [[Languages.br.params.wrapper.content.item]]
        weight = 1
        description = "Conhecerem a Cristo como salvador"
      [[Languages.br.params.wrapper.content.item]]
        weight = 2
        description = "Amadurecerem na vida cristã"
      [[Languages.br.params.wrapper.content.item]]
        weight = 3
        description = "Participarem de grupos pequenos (conexões)"
      [[Languages.br.params.wrapper.content.item]]
        weight = 4
        description = "Atuarem no ministério exercendo seus dons no serviço ao próximo"
      [[Languages.br.params.wrapper.content.item]]
        weight = 5
        description = "Fazerem discípulos de Jesus"
      [[Languages.br.params.wrapper.content.item]]
        weight = 6
        description = "Sustentarem a igreja local, projetos missionários e ações humanitárias"

  [Languages.br.params.believe]
    enable = true
    title = "Drop us a note"
    [Languages.br.params.believe.box]
      title = "Na PBC, acreditamos. . . "
    [Languages.br.params.believe.content]
      [[Languages.br.params.believe.content.item]]
        weight = 1
        description = "Na Bíblia como a infalível e inspirada Palavra de Deus (2 Tm 3:15-16), nossa única regra de fé e conduta."
      [[Languages.br.params.believe.content.item]]
        weight = 2
        description = "Em um só Deus eternamente existente em três pessoas: Pai, Filho e Espírito Santo. (Dt 6:4; Mt 28:19; Mc 12:29; 2 Co 13:13)"
      [[Languages.br.params.believe.content.item]]
        weight = 3
        description = "No nascimento virginal de Jesus Cristo (Is 7:14; Mt 1:22-23) , sua morte vicária e expiatória (1 Co 15:3; 1 Pe 2:24; 3:18 ), na sua ressurreição física (Rm 8:34) e na sua ascensão ao Pai. (At 1:10-11)"
      [[Languages.br.params.believe.content.item]]
        weight = 4
        description = "Que o homem é pecador e está separado de Deus e somente pela fé no sacrifício vicário e expiatório de Jesus Cristo pode ser reconciliado com Deus. (Rm 3:23-24; 6:23; At 3:19; 10:43)"
      [[Languages.br.params.believe.content.item]]
        weight = 5
        description = "Na salvação através do sangue de Jesus Cristo. (Rm 3:24-25; 1 Jo 5:10; Rm 10:13)"
      [[Languages.br.params.believe.content.item]]
        weight = 6
        description = "No batismo nas águas. (Mt 28:19; Rm 6:1-4)"
      [[Languages.br.params.believe.content.item]]
        weight = 7
        description = "Na cura divina através da obra redentora de Jesus na cruz. (Is 53:4; Mt 8:16-17; Tg 5:14-15)"
      [[Languages.br.params.believe.content.item]]
        weight = 8
        description = "Na plenitude do Espírito Santo, a qual será acompanhada por dons espirituais que são distribuídos por Deus para a edificação da igreja local. (At 2:4; 10:44-46; Ef 5:18; 1 Co 12:1-11; Rm 12:4-8; Ef 4:11-12)"
      [[Languages.br.params.believe.content.item]]
        weight = 9
        description = "No poder santificador do Espírito Santo, que capacita o cristão a viver uma vida santa. (1 Co 6:11; 2 Co 5:17; Hb 12:14; 1 Pe 1:2,15-16)"
      [[Languages.br.params.believe.content.item]]
        weight = 10
        description = "Na segunda vinda do Senhor Jesus Cristo. (Mt 24:30; 1 Ts 4:16-17; 1 Co 15:51-55; Ap 1:7; 19:7-9)"
      [[Languages.br.params.believe.content.item]]
        weight = 11
        description = "Na vida eterna com Deus para os salvos e na perdição eterna para os não salvos. (Mt 25:41,46; Jo 3:16-18; At 24:15; Lc 14:14; Ap 20:11-15)"
      [[Languages.br.params.believe.content.item]]
        weight = 12
        description = "Na igreja constituída por pessoas que de livre vontade congregam-se com a finalidade de prestarem culto a Deus, observarem as ordenanças de Jesus, meditarem nos ensinamentos bíblicos para a edificação mútua e para a propagação do Evangelho. (At 2:41-42; Mt18:15-17)"
      [[Languages.br.params.believe.content.item]]
        weight = 13
        description = "Na responsabilidade individual e intransferível de cada cristão no cumprimento da “Grande Comissão” dada por Jesus. (Mt 28:18-20; At 1:8; 1 Jo 2:6)"

  [Languages.br.params.give]
    enable = true
    [Languages.br.params.give.box]
      title = "Nosso Compromisso"
      subtitle = "A PBC tem um compromisso em alcançar todos que estão longe de Deus, demonstrando o Seu amor através de atos de compaixão. Temos o privilégio de cooperar através dos nossos dízimos e ofertas."
      description = "Onde as minhas doações são aplicadas?"
      give = "Ao clicar no botão logo abaixo, será exibido um formulário seguro online para colocar os dados do seu cartão e enviar a sua contribuição voluntária para a PBC. Escolha enviar seu dízimo ou faça a sua doação para qualquer um de nossos ministérios e/ou projetos missionários, atividades sociais locais e ações humanitárias."
      caption = "Doe"
      url = "http://give.pbc.place"

    [Languages.br.params.give.content]
      [[Languages.br.params.give.content.item]]
        weight = 1
        title = "Dízimos"
        description = "Possibilita a operação do dia-a-dia da igreja, dos seus ministérios e dos serviços prestados."
      [[Languages.br.params.give.content.item]]
        weight = 2
        title = "Missões"
        description = "Estabelece apoio contínuo aos nossos missionários."
      [[Languages.br.params.give.content.item]]
        weight = 3
        title = "Oferta"
        description = "Oportunidades surgem periodicamente para designar apoio financeiro a um ministério ou grupo específico."

  [Languages.br.params.blog]
    enable = true
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

  [Languages.br.params.live]
    enable = true
    title = ""
    content = ""
    [Languages.br.params.live.button]
      caption = "Assista aos nossos cultos Ao Vivo, Todos os Domingos @11AM"
      url = "http://live.pbc.place"

  [Languages.br.params.call]
    enable = true
    title = "COMO CHEGAR"
    paragraph = "Estamos localizados na cidade de Saugus, acessível pela rota 1 e próximo ao Square One Mall. Nosso endereço é 47 Adams Avenue, Saugus, MA, 01906."

  [Languages.br.params.contact]
    enable = true
    title = "Drop us a note"
    videomp4 = "video/saugus_pbc_video.mp4"
    videoogg = "video/saugus_pbc_video.ogg"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [Languages.br.params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [Languages.br.params.contact.box]
      title = "Visite-nos"
      address = "47 Adams Avenus, Saugus, MA, 01906"
      email = "Email: office@pbc.place"
      phone = "Telefone: (617) 354-4557"
    [Languages.br.params.contact.gmaps]
      title = "Estamos localizados na cidade de Saugus, acessível pela rota 1 e próximo ao Square One Mall."


  ######## english language
  [Languages.en]
  languageName = "us"
    weight = 2
    languageCode = "en-us"
    title = "PBC PLACE - A Place for New Beginnings"
    baseURL = "https://www.pbc.place/"
    dateFormat = "January 2, 2006"
    home = "Home"
    
  [Languages.en.menu]

    [[Languages.en.menu.header]]
      weight = 2
      name = "What we Believe"
      url = "/believe"
    [[Languages.en.menu.header]]
      weight = 3
      name = "Our Activities"
      url = "/activities"
    [[Languages.en.menu.header]]
      weight = 4
      name = "Visit us"
      url = "/contact"
    [[Languages.en.menu.header]]
      weight = 5
      name = "Give"
      url = "/give"

    [[Languages.en.menu.footer]]
      weight = 2
      name = "What we Believe"
      url = "/believe"
    [[Languages.en.menu.footer]]
      weight = 3
      name = "Our Activities"
      url = "/activities"
    [[Languages.en.menu.footer]]
      weight = 4
      name = "Visit us"
      url = "/contact"
    [[Languages.en.menu.footer]]
      weight = 5
      name = "Give"
      url = "/give"

  [Languages.en.params.slider]
    enable = true
    title = "PBC PLACE<br> A Place for New Beginnings"
    subtitle = "We are a vibrant and exciting church with a contemporary worship celebration, a variety of expressions of praise, and a strong biblical grounding. Our activities are bilingual."

  [Languages.en.params.wrapper]
    enable = true
    image = "img/church_front_people.jpg"
    title = "About Us"
    italic = "We want to lead people to worship and serve God with joy and understanding, challenging them to: "
    [Languages.en.params.wrapper.content]
      [[Languages.en.params.wrapper.content.item]]
        weight = 1
        description = "Know Christ as Savior"
      [[Languages.en.params.wrapper.content.item]]
        weight = 2
        description = "Mature in the Christian life"
      [[Languages.en.params.wrapper.content.item]]
        weight = 3
        description = "Participate in small groups (connections)"
      [[Languages.en.params.wrapper.content.item]]
        weight = 4
        description = "Act in the ministry exercising their gifts in service to others"
      [[Languages.en.params.wrapper.content.item]]
        weight = 5
        description = "Make disciples of Jesus"
      [[Languages.en.params.wrapper.content.item]]
        weight = 6
        description = "Support the local church, missionary projects and humanitarian actions"

  [Languages.en.params.believe]
    enable = true
    title = "Drop us a note"
    [Languages.en.params.believe.box]
      title = "At PBC we believe. . . "
    [Languages.en.params.believe.content]
      [[Languages.en.params.believe.content.item]]
        weight = 1
        description = "In the Bible as the infallible and inspired Word of God (2 Tim. 3: 15-16), our only rule of faith and conduct."
      [[Languages.en.params.believe.content.item]]
        weight = 2
        description = "In one God eternally existing in three persons: Father, Son and Holy Spirit. (Deuteronomy 6: 4, Matthew 28:19, Mark 12:29, 2 Cor 13:13)"
      [[Languages.en.params.believe.content.item]]
        weight = 3
        description = "In the virgin birth of Jesus Christ (Isa 7:14, Mt 1: 22-23), his vicarious and atoning death (1 Cor 15: 3; 1 Pe 2:24; 3:18), in his physical resurrection (Rom 8 : 34) and in his ascension to the Father (Acts 1: 10-11)"
      [[Languages.en.params.believe.content.item]]
        weight = 4
        description = "That man is sinful and separated from God, and only by faith in the vicarious and atoning sacrifice of Jesus Christ can he be reconciled to God. (Romans 3: 23-24, 6:23, Acts 3:19, 10:43)"
      [[Languages.en.params.believe.content.item]]
        weight = 5
        description = "In salvation through the blood of Jesus Christ. (Romans 3: 24-25, 1 John 5:10, Romans 10:13)"
      [[Languages.en.params.believe.content.item]]
        weight = 6
        description = "In water baptism. (Matthew 28:19; Rom 6: 1-4)"
      [[Languages.en.params.believe.content.item]]
        weight = 7
        description = "In divine healing through the redemptive work of Jesus on the cross. (Isaiah 53: 4, Mt 8: 16-17, James 5: 14-15)"
      [[Languages.en.params.believe.content.item]]
        weight = 8
        description = "In the fullness of the Holy Spirit, which will be accompanied by spiritual gifts that are distributed by God to the edification of the local church. (Acts 2: 4, 10: 44-46, Ephesians 5:18, 1 Cor 12: 1-11, Rom 12: 4-8, Eph 4: 11-12)"
      [[Languages.en.params.believe.content.item]]
        weight = 9
        description = "In the sanctifying power of the Holy Spirit, which enables the Christian to live a holy life. (1 Corinthians 6:11, 2 Corinthians 5:17, Heb 12:14, 1 Peter 1: 2,15-16)"
      [[Languages.en.params.believe.content.item]]
        weight = 10
        description = "At the second coming of the Lord Jesus Christ. (Mt 24:30, 1 Thess 4: 16-17, 1 Cor 15: 51-55, Rev 1: 7, 19: 7-9)"
      [[Languages.en.params.believe.content.item]]
        weight = 11
        description = "In eternal life with God for the saved and eternal damnation for the unsaved. (Matthew 25: 41-46, John 3: 16-18, Acts 24:15, Luke 14:14, Revelation 20: 11-15)"
      [[Languages.en.params.believe.content.item]]
        weight = 12
        description = "In the church, made up of people which, in free will, congregate for the purpose of worshiping God, observing the ordinances of Jesus, meditating on the biblical teachings for mutual edification and the propagation of the Gospel. (Acts 2: 41-42; Mt 18: 15-17)"
      [[Languages.en.params.believe.content.item]]
        weight = 13
        description = "In the individual and untransferable responsibility of each Christian in the fulfillment of the 'Great Commission' given by Jesus. (Matthew 28: 18-20, Acts 1: 8, 1 John 2: 6)"

  [Languages.en.params.give]
    enable = true
    [Languages.en.params.give.box]
      title = "Our Commitment"
      subtitle = "PBC is committed to reaching those who are far from God, unleashing unprecedented levels of compassion into a broken world. We have the privilege of partnering with God's work in the world by using our gifts and resources through the local church."
      description = "Where do my donations go?"
      give = "Send through our secure online form, your tithes or offerings to any of our ministries. Click on the button below to start your secure process."
      caption = "Give"
      url = "http://give.pbc.place"

    [Languages.en.params.give.content]
      [[Languages.en.params.give.content.item]]
        weight = 1
        title = "Tithes"
        description = "Funds and makes possible the day-to-day ministries and services of the church."
      [[Languages.en.params.give.content.item]]
        weight = 2
        title = "Missions"
        description = "Offers continuous financial support to our missionaries throughout the world."
      [[Languages.en.params.give.content.item]]
        weight = 3
        title = "Special"
        description = "Periodically, opportunities to designate a donation to a specific ministry initiative become available."


  [Languages.en.params.blog]
    enable = true
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

  [Languages.en.params.live]
    enable = true
    title = ""
    content = ""
    [Languages.en.params.live.button]
      caption = "Watch us Live, Every Sunday @11AM"
      url = "http://live.pbc.place"

  [Languages.en.params.call]
    enable = true
    title = "VISIT US"
    paragraph = "We are located in Saugus, easily accessible via US1 and next to the Square One Mall. Our address is 47 Adams Avenue, Saugus, MA, 01906."

  [Languages.en.params.contact]
    enable = true
    title = "Drop us a note"
    videomp4 = "video/saugus_pbc_video.mp4"
    videoogg = "video/saugus_pbc_video.ogg"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [Languages.en.params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [Languages.en.params.contact.box]
      title = "Stop by for a visit"
      address = "47 Adams Avenus, Saugus, MA, 01906"
      email = "Email: office@pbc.place"
      phone = "Phone: (617) 354-4557"
    [Languages.en.params.contact.gmaps]
      title = "We are located in Saugus, easily accessible via US1 and next to the Square One Mall."
